import {ReactNode} from 'react';
import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import Head from 'next/head';
import {QueryClientProviderWithClient} from '@/_components/QueryClientProviderWithClient';
import AuthSession from '@/_components/AuthSession';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Blog',
  description: 'Generated by create next app',
};
export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body className={`${inter.className}`}>
          <QueryClientProviderWithClient>
            <AuthSession>
              <div>{children}</div>
            </AuthSession>
          </QueryClientProviderWithClient>
        </body>
      </html>
    </>
  );
}
